---
title: "PreprocessCoordinates"
output: html_document
date: "2024-04-24"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
#knitr::opts_knit$set(root.dir = '~/Downloads/archive')
setwd('C:/Users/Kyle Tran/Downloads')
```

```{r}
library(shiny)
library(leaflet)
library(lubridate)
library(sf)
library(tigris)
library(plotly)
library(dplyr)
library(ggplot2)
options(tigris_use_cache = TRUE)
```

```{r}
setwd('C:/Users/Kyle Tran/Downloads')
ufo_data = read.csv("ufoData.csv")
#ufo_data <- read.csv("scrubbed.csv")

ufo_data$datetime <- as.POSIXct(ufo_data$datetime, format = "%m/%d/%Y %H:%M", errors="coerce")
ufo_data <- ufo_data[!is.na(ufo_data$datetime), ]
ufo_data <- ufo_data[!ufo_data$state %in% c("", " "), ]
ufo_data <- ufo_data %>% rename(duration = duration..seconds.)
ufo_data$shape <- ifelse(ufo_data$shape == "", "unknown", ufo_data$shape)
ufo_data$duration <- as.numeric(as.character(ufo_data$duration))
ufo_data$latitude <- as.numeric(ufo_data$latitude)
ufo_data$longitude <- as.numeric(ufo_data$longitude)
ufo_data$state = toupper(ufo_data$state)
```

```{r}
#0 - Extracting Latitude and Longitude and Using Spatial Analysis to Clean Data
#a. making coordinates data frame
latitude = as.numeric(ufo_data$latitude)
longitude = as.numeric(ufo_data$longitude)
coordinates <- data.frame(latitude, longitude)
coordinates <- coordinates %>% 
  filter(!is.na(latitude) & !is.na(longitude))
coordinates <- st_as_sf(coordinates, coords = c("longitude", "latitude"), crs = 4326)

#b. getting state data from package to compare state boundaries
state_data <- states(cb = TRUE, class = "sf")
state_data <- st_transform(state_data, st_crs(coordinates))

#c. comparing the coordinates
results <- st_join(coordinates, state_data, join = st_within)
coordinates <- as.data.frame(st_coordinates(results$geometry))
results <- results %>%
  mutate(latitude = coordinates$Y,
         longitude = coordinates$X)
results <- results %>% 
  select(latitude, longitude, state_abb = STUSPS)
```

```{r}
final_df <- as.data.frame(results)%>%select(-geometry)
final_df <- inner_join(ufo_data, results, by = c("latitude", "longitude")) %>% distinct()
final_df <- final_df %>% filter(state == state_abb | (country != "us" & country != ""))
final_df$state = toupper(final_df$state)
final_df$year = year(final_df$datetime)
final_df$time_of_day <- case_when(
  hour(final_df$datetime) < 12 ~ "Morning",
  hour(final_df$datetime) < 18 ~ "Day",
  TRUE ~ "Night"
)
```

```{r}
final_df$state_abb <- NULL
final_df$geometry <- NULL
final_df$duration..hours.min. <- NULL
View(final_df)
```

```{r}
# save(final_df, file="results.Rda")
saveRDS(final_df, file="results.Rda")
```